server:
  port: 2020

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cvideo1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 2
  redis:
    host: 111.230.32.142
    port: 6379
  thymeleaf:
    cache: false